### ISSUE TITLE
Query that finds only latest Entities

### ISSUE THREAD

**Issue by Faketa** [Gamua/Flox-AS3#7]
Hi
Could you please provide me with a Query example that finds only latest Entities based on "createdAt" index? I would like to find e.g. 10 newest Entities. Is there any posibility to do that?
I tried to use:
'''
var query:Query = new Query(MyEntit);
query.limit = 10;
query.orderBy = "createdAt ASC";
'''
I receive 10 Entities but not newest

**Comment by rwolffgang** [comment]
Did you try “createdAt DESC”?

**Comment by PrimaryFeather** [comment]
rwolffgang is right — `createdAt DESC` should do the trick! Think of a date as the number of seconds since 1970; you'll want the higher numbers first to get the (say) 10 newest entities.

Don't forget to add an index for "createdAt", too!

**Comment by Faketa** [comment]
thank you, DESC works for me.
